### ISSUE TITLE
Locale Maintaining 

### ISSUE THREAD

**Issue by ghost** [hangoutsbot/hangoutsbot-locales#1]
Create a file hangoutsbot.po in en folder and create a blank en file with the strings we use and reference them right.

**Comment by ghost** [comment]
Refer to hangoutsbot/hangoutsbot#155

**Comment by endofline** [comment]
Just a quick update here: to set the bot language, `export HANGOUTSBOT_LOCALE=<language>` (re:  https://github.com/hangoutsbot/hangoutsbot/commit/baa98806aa431f0db5e02a380b153dbf1b7fba0e)

**Comment by ghost** [comment]
Could we latter integrate this with /bot roomlanguage?

**Comment by ghost** [comment]
Started. 
Following TODO order:
- [x] **init**.py
- [x] commands.py
- [x] config.py
- [x] handlers.py
- [x] hangupsbot.py
- [x] utils.py
- [x] hooks/**init**.py
- [x] hooks/chatlogger/**init**.py
- [x] hooks/chatlogger/writer.py
- [x] hooks/hubotsend/**init**.py
- [x] hooks/hubotsend/post.py
- [x] parsers/**init**.py
- [x] parsers/kludgy_html_parser.py
- [x] plugins/image_linker_reddit/*
- [x] plugins/image_screenshot/*
- [ ] plugins/[one by one in alphabetical order] 
- [ ] sinks/generic/[one by one in alphabetical order] 
- [ ] sinks/github/*
- [ ] sinks/gitlab/*
- [ ] sinks/google/*
- [ ] sinks/hubotrecive/*
- [ ] sinks/*
- [ ] tests/*

**Comment by endofline** [comment]
I've created and uploaded a list of source files requiring translation (based on these instructions: http://stackoverflow.com/a/1079473) - as far as I can tell it excludes non-user-visible message strings.

the `messages.pot` file is a reference file that can be used by `msgmerge` to update existing translation files and should be kept up to date by running the following (or similar) in a localised hangoutsbot project:

```
xgettext --files-from=POTFILES.in --directory=.. --output=messages.pot
```

I think I missed the sinks though, will add that in later - but I'm not sure if any of them actually have user-visible messages.

**Comment by endofline** [comment]
To add to the above, I've added shell automation for generating the reference POT and merge-compiling it with existing translation. I've also created a preliminary wiki page to describe how to use it: https://github.com/hangoutsbot/hangoutsbot-locales/wiki - feel free to change/comment/etc on it :)

**Comment by ghost** [comment]
@endofline so no need for me to continue my manual update then? 
:(

**Comment by endofline** [comment]
lol @00svbeon sorry bout that :sweat_smile:  just felt it needed automation - merging won't disrupt current working files I think - `msgmerge` keeps existing `msgstr`s - hope it will be easier since both the framework and plugins are undergoing a lot of refactoring now. if there are any other issues with the automation, just let know here or in other issues, my `gettext` and bash scripting knowledge is years out-of-date so I'm sure there's a lot more room for improvement.

**Comment by ghost** [comment]
Yeah mine knowledge if it too, that's why iImade it manual 😀
Thanks for automating it!!

**Comment by ghost** [comment]
I'll remove the old files!

**Comment by ghost** [comment]
We're now automatically up to date, closing this
